### ISSUE TITLE
Release next version on NPM

### ISSUE THREAD

**Issue by cvializ** [robertknight/xar-js#3]
I installed `xar-js` on NPM and I encountered the "exceptions on empty files" (#2). It looks like v0.1.2 doesn't have that fix in it. Could you please update the version and deploy a new package to npm? Currently I'm working around that by installing directly from Github, but that isn't ideal. Thanks in advance.

**Comment by robertknight** [comment]
Done. Released as v0.2.0. Sorry about that.

**Comment by cvializ** [comment]
Hey, that's all good. Thank you!
