### ISSUE TITLE
Info: Additional instructions for preparing certificates for creating Safari extensions

### ISSUE THREAD

**Issue by pavelstudeny** [robertknight/xar-js#4]
Hi,

just for info, you might want to check out my new instructions at https://github.com/avast/safariextz regarding a private key format https://github.com/avast/safariextz/commit/99edae9d453c093da00fb9394c2bae5bc738e673.

And, by the way, Safari 9 on El Captain usually ignores extension installed by drag&drop. I'm wondering whether you also ran into this issue and possibly resolved it. So far, it seems that drag&drop invokes Safari directly, while a double click runs a webkit process. Extensions in store are fine.

Pavel

**Comment by robertknight** [comment]
Thanks @pavelstudeny , I'll close this issue as it is indeed not a bug report but will leave it here for others to search for.

> And, by the way, Safari 9 on El Captain usually ignores extension installed by drag&drop.
> I'm wondering whether you also ran into this issue and possibly resolved it. 

I haven't tested with Safari under El Capitan yet. I changed jobs late last year and stopped working on the Safari extension for Mendeley. I will most likely be working on one for [Hypothesis](https://hypothes.is) later on this year though.
