### ISSUE TITLE
Segmentation fault: core dumped

### ISSUE THREAD

**Issue by Anacondo** [robertknight/xar-js#7]
I think I found a pretty weird error with XAR while doing a whole system backup. I get a "Segmentation fault: core dumped" error after a while that I can't reproduce with TAR and seems to be isolated to one particular folder in my system.

Right now I can reproduce it by running XAR on this location:

> /home/steam/Steam/steamapps/common/Counter-Strike Source Dedicated Server/cstrike/maps

I'm using the command:

> xar -cvalf "[backup_location]/backup.xar.xz" "/home/steam/Steam/steamapps/common/Counter-Strike Source Dedicated Server/cstrike/maps"

It always crashes when it reaches the same file. However, if I XAR that file directly it does work with no problems. The file itself looks ok and can be opened with no problems. Here's a sample output:

> $ xar -cvalf /mnt/ext_hdd1/backups/backup_test.xar.gz *
> aim_deagle7k.bsp
> aim_deagle7k.nav
> awp_india_v2.bsp
> awp_india_v2.nav
> cs_747_css.bsp
> Segmentation fault (core dumped)

The crash doesn't seem to be related to compression. I tried lzma, gzip and no compression and it always crashes when I try to XAR the contents of that folder. The file system is ext4 and fsck shows no errors whatsoever.

This is dmesg's output after running the above XAR command:

> [Sun Apr 17 14:23:15 2016] xar[19243]: segfault at 0 ip 00007fabb1498e22 sp 00007ffde83bcfb0 error 6 in libxar.so.1[7fabb1486000+17000]

This is my first bug report, so please let me know if there's anything further I should add.

**Comment by robertknight** [comment]
Hello @Anacondo - Your report refers to a command line tool called 'xar' which is not related to this repository. xar-js is a JavaScript library for reading and writing '.xar' archives.
