### ISSUE TITLE
RSA signature size isn't fixed

### ISSUE THREAD

**Issue by palant** [robertknight/xar-js#9]
Your code is hardcoding RSA signature size as 256 bytes. Based on that you seem to be using a 2048 bit key - signature length is actually equal to key length. With a 4096 bit key it will be 512 bytes.

**Comment by robertknight** [comment]
Thanks @palant - I've created a PR to resolve the issue (https://github.com/robertknight/xar-js/issues/10). Perhaps you could have a look at it and check that it makes sense?

Do you know if Apple have changed the Safari Developer Certificates they issue to use 4096-bit keys?

**Comment by palant** [comment]
> Do you know if Apple have changed the Safari Developer Certificates they issue to use 4096-bit keys?

This length is related to the private key, not the certificate. And the private key is under your control, Apple doesn't get to see it. So you can generate a 4096 bit private key and Apple will give you a certificate for it.

The PR makes sense, I [solved this in the same way](https://hg.adblockplus.org/buildtools/file/cc9f396fb59b/xarfile.py#l115). I commented on two things there but these don't affect functionality.
